version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres:12.5
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}_${NODE_ENV}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - pg-network
    restart: unless-stopped

networks:
  pg-network:
    driver: bridge

volumes:
  pgdata:
    external: true


