name: Pull Request

on: pull_request

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:14
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: financial_testing
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Run tests
        run: yarn coverage
        env:
          PORT: 80
          HOST: 0.0.0.0
          NODE_ENV: testing
          APP_KEY: iq90dswa90fi091i20fdisa9ujf9p1jfdp
          DB_CONNECTION: pg
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_NAME: financial
          DB_PORT: 5432
          DB_HOST: postgres
          TZ: America/Sao_Paulo
          LOGGING: false
          HEADER_API_KEY: testing

